name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'
change-template: '- #$NUMBER $TITLE @$AUTHOR'
sort-direction: ascending
exclude-labels:
  - 'skip-changelog'
categories:
  - title: '⚒️ Breaking Changes'
    labels:
      - breaking-change

  - title: '🚀 Features'
    labels:
      - 'feature request'
      - 'enhancement'

  - title: '🐛 Bug Fixes'
    labels:
      - 'fix'
      - 'bugfix'
      - 'bug'

  - title: '🧬 Changes to Charge Owner informations'
    labels:
      - chargeowner
      - chargeowners

  - title: '🧬 New Charge Owner(s) added'
    labels:
      - 'new chargeowner'

  - title: '🧰 Maintenance'
    label: 'chore'

  - title: '📦 Dependencies'
    labels:
      - 'dependencies'

version-resolver:
  major:
    labels:
      - 'major'
  minor:
    labels:
      - 'minor'
  patch:
    labels:
      - 'patch'
  default: patch
template: |
  ## Changes

  $CHANGES

autolabeler:
  - label: 'bug'
    branch:
      - '/fix\/.+/'
  - label: 'feature request'
    branch:
      - '/feature\/.+/'
